apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: evil
  name: evil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evil
  strategy: {}
  template:
    metadata:
      labels:
        app: evil
    spec:
      containers:
      - image: teamsis2022/evil-service:APP_VERSION
        name: evil-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        resources: {}
